version: "3.7"

services:
  # db:
  #   image: mysql:5.7
  #   user: 1000:1000
  #   container_name: ${PROJECT_NAME}-db
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   volumes:
  #     - ../db/data:/var/lib/mysql
  #     - ../db/dump:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${PROJECT_NAME}
  #     MYSQL_USER: ${PROJECT_NAME}
  #     MYSQL_PASSWORD: ${PROJECT_NAME}
  #     MYSQL_DATABASE: ${PROJECT_NAME}
  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: ${PROJECT_NAME}-db
    restart: unless-stopped
    tty: true
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${PROJECT_NAME}
      MYSQL_USER: ${PROJECT_NAME}
      MYSQL_PASSWORD: ${PROJECT_NAME}
      MYSQL_DATABASE: ${PROJECT_NAME}
      # SERVICE_TAGS: dev
      # SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ../db/dump:/docker-entrypoint-initdb.d/
      - ../db/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  # nginx:
  #   image: nginx
  #   container_name: ${PROJECT_NAME}-nginx
  #   restart: always
  #   ports:
  #     - ${NGINX_PORT}:80
  #   volumes:
  #     - ${SRC_ROOT}:/app
  #     - ../nginx/sites/local.conf:/etc/nginx/conf.d/default.conf
  #     - ../nginx/local.laravel.conf:/etc/nginx/local.default.conf
  #   links:
  #     - app
  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ${SRC_ROOT}:/app
      - ../nginx/sites/local.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/local.laravel.conf:/etc/nginx/local.laravel.conf
    
  app:
    build: ./../laravel
    image: digitalocean.com/php
    container_name: ${PROJECT_NAME}-app
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - ${SRC_ROOT}:/app
      - ${SSH_PATH}:/root/.ssh
      - ../php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    networks:
      - app-network
    environment: 
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      MYSQL_PORT: ${MYSQL_PORT}
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
      TEST_RUNTIME_PATH: /tmp/runtime

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local